name: flutter_sound_record
description: Audio recorder from microphone to a given file path with multiple codecs, bit rate and sampling rate options.
version: 3.3.2
homepage: https://github.com/josephcrowell/flutter_sound_record/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sound_record_platform_interface:
    path: flutter_sound_record_platform_interface
  flutter_sound_record_web:
    path: flutter_sound_record_web

#dependency_overrides:
#   flutter_sound_record_platform_interface:
#     path: flutter_sound_record_platform_interface
#   flutter_sound_record_web:
#     path: flutter_sound_record_web

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.josephcrowell.flutter_sound_record
        pluginClass: FlutterSoundRecordPlugin
      ios:
        pluginClass: FlutterSoundRecordPlugin
      web:
        default_package: flutter_sound_record_web
