name: flutter_sound_record_platform_interface
description: A common platform interface for the flutter_sound_record plugin.
homepage: https://github.com/josephcrowell/flutter_sound_record//tree/master/flutter_sound_record_platform_interface
version: 0.3.1

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
